config/routes.rb
ShibShibBlastic::Application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

    match "new_post" => "posts#new"
    match "profile" => "users#show"
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
    devise_scope :user do
     get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    match "index" => "welcome#index"
    match "mvote" => "welcome#mvote"
    match "about" => "welcome#about"
    match "faq" => "welcome#faq"
    get "welcome/index"
    get "welcome/latest"
    get 'tags/:tag', to: 'posts#index', as: :tag

    resources :welcome
    resources :posts do
      get 'vote'
      get 'mark_inappropriate'
    end

    resources :users
    resources :posts

    root :to => 'welcome#index'
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # before_filter :authenticate_user!, :except=>"index"
  def index
    @posts = Post.where(:is_inappropriate => false).page(params[:page]).order("created_at DESC").per_page(10)
  end
  
  def mvote
    @posts = Post.where(:is_inappropriate => false).page(params[:page]).order('vote_count DESC').per_page(10)
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h2><%= t 'footer.all_about' %></h2>
<%= image_tag("about.jpg", :alt => "about", :style=>"margin:0; padding:0") %>

app/views/welcome/faq.html.erb
<h2><%= t 'footer.all_faq' %></h2>
<%= image_tag("faq.jpg", :alt => "faq", :style=>"margin:0; padding:0") %>

app/views/welcome/index.html.erb
<div class="tabbable" style="margin-bottom: 9px;">
  <ul class="nav nav-tabs">
    <li class="active"><a href="<%= index_path %>"><%= t 'tabs.latest' %></a></li>
    <li><a href="<%= mvote_path %>"><%= t 'tabs.most_voted' %></a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="0">
      <div id="posts">
      <%= render @posts %>
      </div>
    </div>
  </div> <!-- /tab-content -->
</div> <!-- /tabbable -->
<%= will_paginate(@posts, :more => true) %>

app/views/welcome/index.mobile.erb
<% if params[:locale] == 'ar'
     @lang = "ar_AR"
     @tlang = "ar"
   else
     @lang = "en_US"
     @tlang = "en"
   end %>
<div data-role="header" data-position="inline" class="ui-body-b">
  <h1 class="ui-btn-left" ><%= title %></h1>
  <form name="form1" >
  <select name="select" onchange="goto(this.form)" data-native-menu="false">
    <option><%= t 'mobile.options' %></option>
    <% if user_signed_in? then %>
      <option value="<%= new_post_path %>"><%="#{t 'header.new_post'}"%></option>
      <option value="<%= destroy_user_session_path %>"><%="#{t 'header.sign_out'}"%></option>
    <% else %>
      <option value="<%= new_user_session_path %>"><%="#{t 'header.login'}"%></option>
      <option value="<%= new_user_registration_path %>"><%="#{t 'header.sign_up'}"%></option>
    <% end %>
    <option value="<%= index_path %>"><%= t 'tabs.latest' %></option>
    <option value="<%= mvote_path %>"><%= t 'tabs.most_voted' %></option>
    <option value="<%= root_url(:mobile => 0) %>"><%= t 'mobile.full_version' %></option>
  </select>
  </form>
</div>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

<%= render @posts %>
<div class="center">
<%= will_paginate(@posts, :more => true, :class => "digg_pagination", :page_links => false) %>
</div>

app/views/welcome/latest.html.erb
<div class="tabbable" style="margin-bottom: 9px;">
  <ul class="nav nav-tabs">
    <li><a href="<%= index_path %>"><%= t 'tabs.most_voted' %></a></li>
    <li class="active"><a href="<%= latest_path %>"><%= t 'tabs.latest' %></a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="1">
    <div id="posts">
    <%= render @posts %>
    </div>
    <%= will_paginate(@posts, :more => true) %>
    </div>

    <div class="tab-pane" id="2">
    <div id="posts">
    <%= render @posts %>
    </div>
    <%= will_paginate(@posts, :more => true) %>
    </div>
    </div>
</div> <!-- /tabbable -->

<p id="back-top"><a href="#top"><span></span><%= t 'others.back_to_top' %></a></P>

app/views/welcome/latest.js.erb
$('#posts').append('<%= j render(@posts) %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>
$(document).ajaxComplete(function(){
    try{
        FB.XFBML.parse(); 
    }catch(ex){}
});

app/views/welcome/mvote.html.erb
<div class="tabbable" style="margin-bottom: 9px;">
  <ul class="nav nav-tabs">
    <li><a href="<%= index_path %>"><%= t 'tabs.latest' %></a></li>
    <li class="active"><a href="<%= mvote_path %>"><%= t 'tabs.most_voted' %></a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="1">
      <div id="posts">
      <%= render @posts %>
      </div>
    </div>
  </div> <!-- /tab-content -->
</div> <!-- /tabbable -->
<%= will_paginate(@posts, :more => true) %>

app/views/welcome/mvote.js.erb
$('#posts').append('<%= j render(@posts) %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>
$(document).ajaxComplete(function(){
    try{
        FB.XFBML.parse(); 
    }catch(ex){}
});

app/views/welcome/mvote.mobile.erb
<% if params[:locale] == 'ar'
     @lang = "ar_AR"
     @tlang = "ar"
   else
     @lang = "en_US"
     @tlang = "en"
   end %>
<div data-role="header" data-position="inline" class="ui-body-b">
  <h1 class="ui-btn-left" ><%= title %></h1>
  <form name="form1" >
  <select name="select" onchange="goto(this.form)" data-native-menu="false">
    <option><%= t 'mobile.options' %></option>
    <% if user_signed_in? then %>
      <option value="<%= new_post_path %>"><%="#{t 'header.new_post'}"%></option>
      <option value="<%= destroy_user_session_path %>"><%="#{t 'header.sign_out'}"%></option>
    <% else %>
      <option value="<%= new_user_session_path %>"><%="#{t 'header.login'}"%></option>
      <option value="<%= new_user_registration_path %>"><%="#{t 'header.sign_up'}"%></option>
    <% end %>
    <option value="<%= index_path %>"><%= t 'tabs.latest' %></option>
    <option value="<%= mvote_path %>"><%= t 'tabs.most_voted' %></option>
    <option value="<%= root_url(:mobile => 0) %>"><%= t 'mobile.full_version' %></option>
  </select>
  </form>
</div>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

<%= render @posts %>
<div class="center">
<%= will_paginate(@posts, :more => true, :class => "digg_pagination", :page_links => false) %>
</div>