config/routes.rb
ShibShibBlastic::Application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

    match "new_post" => "posts#new"
    match "profile" => "users#show"
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
    devise_scope :user do
     get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    match "index" => "welcome#index"
    match "mvote" => "welcome#mvote"
    match "about" => "welcome#about"
    match "faq" => "welcome#faq"
    get "welcome/index"
    get "welcome/latest"
    get 'tags/:tag', to: 'posts#index', as: :tag

    resources :welcome
    resources :posts do
      get 'vote'
      get 'mark_inappropriate'
    end

    resources :users
    resources :posts

    root :to => 'welcome#index'
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")

end

app/models/post.rb
class Post < ActiveRecord::Base

  after_save :update_vote_count
  scope :reported, where(:is_inappropriate => true)

  attr_accessible :tag_list, :user_id, :title, :content, :content_html, :image, :vote_count
  acts_as_taggable
  acts_as_voteable
  belongs_to :user
  
  has_attached_file :image,
  :styles => { :large => "720>", :medium => "320>", :thumb => "100x100>" },
  :storage => :s3,
  :bucket => 'ShibShibBlastic',
  :s3_credentials => {
    :access_key_id => "AKIAIISMCRUVUPIWIV2A",
    :secret_access_key => "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"
  }

  auto_html_for :content do
    # html_escape
    image
    dailymotion
    # flickr
    google_video
    metacafe
    # soundcloud
    # twitter
    vimeo
    youtube(:width => 450)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  def self.feed(last)
    self.where("created_at < ? ", last).order('created_at desc').limit(5)
  end
  
  validates_presence_of :title, :if => :content_exists
  validates_presence_of :content, :if => :image_exists
  validates_attachment_presence :image, :if => :content_exists
  validates_attachment_size :image, :less_than=>2.megabyte, :if => Proc.new { |imports| !imports.image_file_name.blank? }

  def update_vote_count
    self.vote_count = self.plusminus
  end

  def image_exists
    image.to_s.include? "missing" #true
  end

  def content_exists
    content.gsub(/\s+/, "").tr("\n","").empty?
  end

end

app/controllers/posts_controller.rb
# encoding: utf-8
class PostsController < ApplicationController
  include AutoHtml

  before_filter :check_user, :only => [:edit, :update, :destroy]
  respond_to :html, :js

  def check_user
   @post = Post.find(params[:id])
   #raise @post.to_yaml
   if current_user.id != @post.user_id
     if !current_user.is_admin
       flash[:alert] = "#{t 'post.unautherized_edit'}"
       redirect_to post_path
     end
   end
  end

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).page(params[:page]).order('created_at DESC').per_page(10)
    else
      redirect_to root_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @title = @post.title

    content_keycap(@post.content) if @post.content.present?

    if request.path != post_path(@post)
      redirect_to @post, status: :moved_permanently
    end
    if @post.is_inappropriate then
      flash[:alert] = "This post has been removed for having inappropriate content"
      redirect_to :root
    end
  end

  def new
    if current_user.nil?
      redirect_to(:root)
    elsif current_user.is_banned
      flash[:alert] = "#{t 'user.banned'}"
      redirect_to(:back)
    end
    @title = t 'header.new_post'
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
    content_keycap(@post.content) if @post.content.present?
    if (params[:locale] == "ar")
      @title = "#{t 'general.edit'}: #{@post.title}"
    else
      @title = "#{t 'general.edit'}ing: #{@post.title}"
    end
  end

  def create
    @title = t 'header.new_post'
    @post = Post.new(params[:post])
    @em = Emoticon.all
    final_content = ""
    @post.content.split(//).each do |c|
      i = @em.map(&:keycap).index c
      if i
        final_content = "#{final_content}#{@em[i].name}"
        
      else
        final_content = "#{final_content}#{c}"
      end
    end
    @post.title = @post.content.split("\r\n")[0] if @post.content.present? && !@post.title.present?
    @post.content = final_content
    # @post.content = auto_html(@post.content) { simple_format; link(:target => 'blank') }
    @post.content = @post.content.to_s.gsub("\r\n", '<br>')
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        current_user.vote_for(@post)
        @post.vote_count = @post.plusminus
        format.html { redirect_to @post, alert: "#{t 'post.create'}" }
        format.mobile { redirect_to @post, alert: "#{t 'post.create'}" }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.mobile { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    @em = Emoticon.all
    new_content = params[:post][:content]
    final_content = ""
    new_content.split(//).each do |c|
      i = @em.map(&:keycap).index c
      if i
        final_content = "#{final_content}#{@em[i].name}"
        
      else
        final_content = "#{final_content}#{c}"
      end
    end
    @post.title = new_content.split("\r\n")[0] if new_content.present? && !@post.title.present?
    new_content = final_content
    # @post.content = auto_html(@post.content) { simple_format; link(:target => 'blank') }
    params[:post][:content] = new_content.to_s.gsub("\r\n", '</br>')
    if @post.user_id == current_user.id then
      if @post.update_attributes(params[:post])
        redirect_to @post, alert: "#{t 'post.update'}"
      else
        render action: "edit"
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user.id) }
      format.json { head :no_content }
    end
  end
  
  def vote
    @post = Post.find(params[:post_id])
    current_user.vote_for(@post) if !current_user.blank?
    @post.vote_count = @post.plusminus
    respond_to do |format|
      format.js
    end
  end
  
  def mark_inappropriate
    if user_signed_in?
      @post = Post.find(params[:post_id])
      @post.is_inappropriate = true
      @post.save!
      flash[:alert] = "#{t 'post.report_notice'}"
      redirect_to root_url
    else
      flash[:alert] = "#{t 'post.login_report'}"
      redirect_to :back
    end
  end

  def content_keycap(content)
    @distro = content
    @em = Emoticon.all
    @distro.to_str.gsub(/:([a-z0-9\+\-_]+):/) do |c|
      i = @em.map(&:name).index c
      if i
        @distro = @distro.gsub(c, @em[i].keycap)    
      end
    end
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="row"><br/>
  <div class="span4">&nbsp;</div>

  <div class="span4">
  <%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if (action_name == "new") %>
        <h2><%= t 'post.new_post' %></h2>
  <% elsif (action_name == "edit") %>
        <h2><%= t 'post.edit_post' %></h2>
  <% end %>
  <%= f.hidden_field :user_id %>
  <%= f.label "#{t 'post.title'}" %> <%= f.text_field :title %>
  <% cont = "" %>
  <% cont = @distro.gsub('<br />', "").gsub('<p>', "").gsub('</p>', "") if @post.content.present? %>
  <%= f.label "#{t 'post.content'}" %> <%= f.text_area :content, :value=>cont, :style=>"resize:none", :cols=>"10", :rows=>"10" %>
  <br /><br /><%= t 'post.or' %> <br /><br /><br />
  <%= f.label "#{t 'post.image'}" %> <%= f.file_field :image %><br />
  <%= if (action_name == "edit")
        "#{t 'post.edit_note'}"
      end %><br />
  <%= f.label "#{t 'post.tags'}" %> <%= f.text_field :tag_list %>
  <br />
  <%= f.submit "#{t 'general.submit'}", :class=>"btn btn-medium" %>
  <br />
  <% end %>
  </div>
</div>

app/views/posts/_form.mobile.erb
<% if params[:locale] == 'ar'
     @lang = "ar_AR"
     @tlang = "ar"
   else
     @lang = "en_US"
     @tlang = "en"
   end %>
<div data-role="header" data-position="inline" class="ui-body-b">
  <h1 class="ui-btn-left" ><%= title %></h1>
  <form name="form1" >
  <select name="select" onchange="goto(this.form)" data-native-menu="false">
    <option><%= t 'mobile.options' %></option>
    <% if user_signed_in? then %>
      <option value="<%= new_post_path %>"><%="#{t 'header.new_post'}" %></option>
      <option value="<%= destroy_user_session_path %>"><%="#{t 'header.sign_out'}"%></option>
    <% else %>
      <option value="<%= new_user_session_path %>"><%="#{t 'header.login'}"%></option>
      <option value="<%= new_user_registration_path %>"><%="#{t 'header.sign_up'}"%></option>
    <% end %>
    <option value="<%= index_path %>"><%= t 'tabs.latest' %></option>
    <option value="<%= mvote_path %>"><%= t 'tabs.most_voted' %></option>
    <option value="<%= root_url(:mobile => 0) %>"><%= t 'mobile.full_version' %></option>
  </select>
  </form>
</div>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

<div class="ui-body center"><br/>
  <%= form_for(@post, :html => {:data => {:ajax => 'false'}})  do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>
  <%= f.label "#{t 'post.title'}" %> <%= f.text_field :title %><br />
  <%= f.label "#{t 'post.content'}" %> <%= f.text_area :content, :class=>"center",:style=>"resize:none; min-height: 250px; min-width: 98% !important;" %>
  <br /><br /><br /><%= t 'post.or' %> <br /><br /><br />
  <%= f.label "#{t 'post.image'}" %><br /><%= f.file_field :image %><br />
  <%= if (action_name == "edit")
        "#{t 'post.edit_note'}"
      end %>
  <br /><br />
  <%= f.submit "#{t 'general.submit'}", :class=>"btn btn-medium", "data-theme"=>"b" %>
  <% end %>
  </div>

app/views/posts/_post.mobile.erb
<div class="ui-body ui-body-d center">
<h3><%= link_to post.title, post %></h3>
<%= if !post.image.url(:medium).include?("missing.png")
      link_to image_tag(post.image.url(:medium), :alt => post.title)
    elsif !post.image.url(:large).include?("missing.png")
      link_to image_tag(post.image.url(:large), :alt => post.title)
    end %>

<div class="text"><%= raw emojify(post.content_html) if post.content.present? %></div>
<!--
<br/>
      
<% if(post.plusminus == 0)
     nlikes = "#{t 'post.no_likes'}"
   elsif(post.plusminus == 1) 
     likes = "#{t 'post.one_like'}"
   elsif(post.plusminus == 2)
     likes = "#{t 'post.two_likes'}"
   elsif(post.plusminus > 2 && post.plusminus < 11)
     nlikes = "#{post.plusminus.to_s}"
     likes = " #{t 'post.three_to_ten_likes'} "
   else
     nlikes = "#{post.plusminus.to_s}"
     likes = " #{t 'post.many_likes'} "
   end %>

<div data-role="controlgroup" data-type="horizontal">
<%= link_to ({:controller=> 'posts', :action=>'vote', :post_id => post.id}), {"data-role"=>"button", "data-inline"=>"true", "data-icon"=>"star", "data-mini"=>"true", "data-iconpos"=>"right", "data-theme"=>"b", :remote => true} do %>
  <span id="votes-<%= post.id %>"><%= nlikes %></span><span><%= likes %></span>
<% end %>


<a href="<%= post_path(post).to_s+'#disqus_thread' %>" data-icon="info" data-role="button" data-inline="true" data-mini="true" data-theme="b" data-iconpos="right"><span style="visibility:hidden;" ><%= "#{t 'post.fake'}" %></span></a>
</div>
-->
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/edit.mobile.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div id="posts">
  <%= render @posts %>
</div>
<%= will_paginate(@posts, :more => true) %>

app/views/posts/index.js.erb
$('#posts').append('<%= j render(@posts) %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>
$(document).ajaxComplete(function(){
    try{
        FB.XFBML.parse(); 
    }catch(ex){}
});

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/new.mobile.erb
<%= render 'form' %>

app/views/posts/show.html.erb
 <script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'Shibshib'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
  var s = document.createElement('script'); s.async = true;
  s.type = 'text/javascript';
  s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>
<% if params[:locale] == 'ar'
     @lang = "ar_AR"
     @tlang = "ar"
   else
     @lang = "en_US"
     @tlang = "en"
   end %>
<div class="well">
  <h1><%= @post.title %></h1>
  <p></p>
  <i class="icon-user"></i>

  <% if(@post.plusminus == 0)
    nlikes = "#{t 'post.no_likes'}"
  elsif(@post.plusminus == 1) 
    likes = "#{t 'post.one_like'}"
  elsif(@post.plusminus == 2)
    likes = "#{t 'post.two_likes'}"
  elsif(@post.plusminus > 2 && @post.plusminus < 11)
    nlikes = "#{@post.plusminus.to_s}"
    likes = " #{t 'post.three_to_ten_likes'} "
  else
    nlikes = "#{@post.plusminus.to_s}"
    likes = " #{t 'post.many_likes'} "
  end %>

  <% if @post.user == nil then %>
    Anonymous
  <% else %>
    <%= link_to @post.user.name, user_path(@post.user) %>
  <% end %> |

  <!-- the below line is needed for Arabic alginment -->
  <i style="visibility:hidden;" ><%= "#{t 'post.fake'}" %></i>

  <i class="icon-time"></i>
  <%= if(params[:locale] == 'ar')
        t = (Time.now - @post.created_at) #to secs
        #check for numbers 3 to 10
        if((t/31104000).ceil > 2 && (t/31104000).ceil < 11) #check years
          "#{t 'post.ago'} #{(t/31104000).ceil} #{t 'others.ar_t_t_years'}"
        elsif((t/2592000).ceil > 2 && (t/2592000).ceil < 11) #check months
          "#{t 'post.ago'} #{(t/2592000).ceil} #{t 'others.ar_t_t_months'}"
        elsif((t/86400).ceil > 2 && (t/86400).ceil < 11) #check days
          "#{t 'post.ago'} #{(t/86400).ceil} #{t 'others.ar_t_t_days'}"
        elsif((t/3600).ceil > 2 && (t/3600).ceil < 11) #check hours
          "#{t 'post.ago'} #{(t/3600).ceil} #{t 'others.ar_t_t_hours'}"
       elsif((t/60).ceil > 2 && (t/60).ceil < 11) #check mins
          "#{t 'post.ago'} #{(t/60).ceil} #{t 'others.ar_t_t_mins'}"
        #check for number 2
        elsif((t/31104000).ceil > 1.5 && (t/31104000).ceil < 3) #check years
          "#{t 'post.ago'} #{t 'others.ar_t_years'}"
        elsif((t/2592000).ceil > 1.5 && (t/2592000).ceil < 3) #check months
          "#{t 'post.ago'} #{t 'others.ar_t_months'}"
        elsif((t/86400).ceil > 1.5 && (t/86400).ceil < 3) #check days
          "#{t 'post.ago'} #{t 'others.ar_t_days'}"
        elsif((t/3600).ceil > 1.5 && (t/3600).ceil < 3) #check hours
          "#{t 'post.ago'} #{t 'others.ar_t_hours'}"
        elsif((t/60).ceil > 1.5 && (t/60).ceil < 3) #check mins
          "#{t 'post.ago'} #{t 'others.ar_t_mins'}"
        #check for number 2
        else
          "#{t 'post.ago'} #{distance_of_time_in_words(Time.now, @post.created_at)}"
        end
      else
        "#{distance_of_time_in_words(Time.now, @post.created_at)}#{t 'post.ago'}"
      end  %> |


  <i class="icon-comment"></i>
  <!-- <fb:comments-count href="http://shibshib.me/posts/<%= @post.id %>"></fb:comments-count> -->
  <a href="<%= post_path(@post).to_s+'#disqus_thread' %>"></a> |

  <i class="icon-heart"></i>
  <%= nlikes.to_s + likes.to_s %>
  <br/><br/>
  <div id="tag_cloud">
  <%= "#{t 'post.show_tags'}: " if @post.tag_list.present? %>
  <% tc = @post.tag_counts.count %>
  <% tag_cloud @post.tag_counts, %w[s m l] do |tag, css_class| %>
    <% tc = tc - 1 %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %> <%= ", " if tc != 0 %>
  <% end %>
  </div>
  <% if ((user_signed_in?) && ((current_user.id == @post.user_id) || (current_user.is_admin?))) then %>
    <br/>
    <div class="btn-group small-break">
      <a class="btn btn-mini" href=" <%= edit_post_path(@post) %> ">
        <i class="icon-edit"></i>
        <%= t 'general.edit' %>
      </a>

      <a class="btn btn-mini" href=" <%= @post %> " data-method="delete" data-confirm="<%= %-#{t 'general.delete_cnfrm'}- %>">
        <i class="icon-remove"></i>
        <%= t 'general.delete' %>
      </a>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.id != @post.user_id %>
      <% if (current_user.is_admin?)  %>
        </br>
      <% end %>
      <a href = "<%= post_path(@post) %>/mark_inappropriate" class="report"><%= t 'post.report' %></a>
    <% end %>
  <% end %>
  <% if current_user == nil %>
    <a href = "<%= post_path(@post) %>/mark_inappropriate" class="report"><%= t 'post.report' %></a>
  <% end %>
</div><!-- end of 1st well -->

<%= image_tag @post.image.url(:large), :class=>'displayed', :alt => @post.title if @post.image.present?%>
<%= emojify(@post.content_html.to_s.gsub('<p>', '<p class="text RTL">')) if @post.content.present? %>

</br></br>
<% if user_signed_in? && current_user.is_admin %>
  <%
    bitly = Bitly.new('o_7t70lsdg3b','R_8006c2ec01704d851dd9bea665ce9f3b')
    page_url = bitly.shorten("http://shibshib.me#{request.fullpath}")
  %>
  <div>
    <textarea readonly="readonly" onclick="this.focus();this.select()">
    <%= @post.title %>

    <%= page_url.short_url %></textarea>
  </div>
<% end %>
<div class="well">
    <ul class='shareLinks' id="shares<%= @post.id %>">
      
     <li>
      <%= link_to ({:controller=> 'posts', :action=>'vote', :post_id => @post.id}), :remote => true do %>
        <span class="btn btn-mini"><i class="icon-heart"></i> <i style="visibility:hidden;" ><%= "#{t 'post.fake'}" %></i><span id="votes-<%= @post.id %>"><%= nlikes %></span><span><%= likes %></span></span>
      <% end %>
      </li>

      <!-- Tweeter -->
      <li>
      <div class="tweet">
      <a target="_blank" href="http://twitter.com/share" class="twitter-share-button" data-url="<%= post_url(@post)%>" data-text="<%= @post.title %>" data-count="none" data-via="shibshibme" data-hashtags="ضحك" data-lang="<%= @tlang %>"></a></div>
      </li>

      <!-- Facebook -->
      <li>
      <div class="fb-like" data-href="<%= post_url(@post)%>" data-send="true" data-layout="button_count" data-width="50" data-show-faces="false" data-font="tahoma" send="false"></div>
      </li>
      
    </ul>
    
      <div class="small-break"></div><br/>

        <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'Shibshib'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

  <div id="comments" class="comments">
    <div class="fb-comments" data-href="http://shibshib.me/posts/<%= @post.id %>" data-num-posts="3" data-width="470"></div>
  </div>
</div><!-- end of 2nd well -->

app/views/posts/show.mobile.erb
<%# encoding: utf-8 %>
<% if params[:locale] == 'ar'
     @lang = "ar_AR"
     @tlang = "ar"
   else
     @lang = "en_US"
     @tlang = "en"
   end %>
<div data-role="header" data-position="inline" class="ui-body-b">
  <h1 class="ui-btn-left" ><%= title %></h1>
  <form name="form1" >
  <select name="select" onchange="goto(this.form)" data-native-menu="false">
    <option><%= t 'mobile.options' %></option>
    <% if user_signed_in? then %>
      <option value="<%= new_post_path %>"><%="#{t 'header.new_post'}"%></option>
      <option value="<%= destroy_user_session_path %>"><%="#{t 'header.sign_out'}"%></option>
    <% else %>
      <option value="<%= new_user_session_path %>"><%="#{t 'header.login'}"%></option>
      <option value="<%= new_user_registration_path %>"><%="#{t 'header.sign_up'}"%></option>
    <% end %>
    <option value="<%= index_path %>"><%= t 'tabs.latest' %></option>
    <option value="<%= mvote_path %>"><%= t 'tabs.most_voted' %></option>
    <option value="<%= root_url(:mobile => 0) %>"><%= t 'mobile.full_version' %></option>
  </select>
  </form>
</div>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

<div class="ui-body ui-body-d center">
  <br/><br/>
  <div class="ui-body-d text"><%= emojify(@post.content_html) if @post.content.present? %>
  <%= image_tag @post.image.url(:medium), :alt => @post.title if @post.image.present? %>
  </div>
  <br/><br/>
  <%
    bitly = Bitly.new('o_7t70lsdg3b','R_8006c2ec01704d851dd9bea665ce9f3b')
    page_url = bitly.shorten("http://shibshib.me#{request.fullpath}")
  %>
  <br/>
  <label for="textarea-a"><%= t 'mobile.share' %></label>
  <div data-role="fieldcontain">
    <textarea name="textarea" id="textarea" readonly="readonly" onclick="this.focus();this.select()">
    <%= @post.title %>
    <%= @distro.gsub('<br />', "\r\n").gsub('<br>', "\r\n") if @post.content.present? %>


    <%= page_url.short_url %></textarea>
  </div>

  <br/>
  <a href="<%= post_path(@post.id-1) %>" data-role="button" data-inline="true" data-theme="b" data-icon="arrow-l"><%= t 'mobile.prev' %></a>
  <a href="<%= post_path(@post.id+1) %>" data-role="button" data-inline="true" data-theme="b" data-icon="arrow-r" data-iconpos="right"><%= t 'mobile.next' %></a>

  <ul class='shareLinks' id="shares<%= @post.id %>">

  <!-- Tweeter -->
  <li><div class="tweet">
    <a target="_blank" href="https://twitter.com/share" class="twitter-share-button" data-url="<%= post_url(@post)%>" data-text="<%= @post.title %>" data-count="none" data-via="shibshibme" data-hashtags="ضحك" data-lang="<%= @tlang %>"></a>
  </div></li>

  <!-- Facebook -->
  <li><div class="fb-like" data-href="<%= post_url(@post)%>" data-send="true" data-layout="button_count" data-width="50" data-show-faces="false" data-font="tahoma" send="false" data-inline="true" value="yoyoyo">
  </div></li>

  </ul>
    <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'Shibshib'; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <div id="disqus_thread"></div>

  <div class="fb-comments" data-href="http://shibshib.me/posts/<%= @post.id %>" data-num-posts="3" data-width="470"></div>

</div>

app/views/posts/vote.js.erb
<% id = "p"+@post.id.to_s %>
<% voteid = '#votes-' + @post.id.to_s %>
<% selecter = '#shares' + @post.id.to_s %>
<% @link = "<a href='http://shibshib.me/users/sign_in'><div id='login-required'><p>#{t 'post.log_to_vote'}</p></div></a>" %>

$("<%= selecter %>").bind("click", function() {
  <% if current_user.nil? %>
    $("<%= selecter %>").before("<%= @link.html_safe %>");
    $("#login-required").fadeOut(4000, function() {$("#login-required").remove();});
  <% else %>
    $("<%= voteid %>").html('');
    $("<%= voteid %>").html(<%= @post.plusminus %>);
  <% end %>
  $(this).unbind( event );
});