config/routes.rb
ShibShibBlastic::Application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

    match "new_post" => "posts#new"
    match "profile" => "users#show"
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
    devise_scope :user do
     get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    match "index" => "welcome#index"
    match "mvote" => "welcome#mvote"
    match "about" => "welcome#about"
    match "faq" => "welcome#faq"
    get "welcome/index"
    get "welcome/latest"
    get 'tags/:tag', to: 'posts#index', as: :tag

    resources :welcome
    resources :posts do
      get 'vote'
      get 'mark_inappropriate'
    end

    resources :users
    resources :posts

    root :to => 'welcome#index'
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")

end

app/views/layouts/_facebook_sdk.html.erb
<div id="fb-root"></div>
<script>
var head = $("head").get(0);  // using jquery
var script2 = document.createElement("script");
script2.innerHTML = "window.FB = null;FB=null;";
head.appendChild(script2);
<% if locale == :ar
     @lang = "ar_AR"
   else
     @lang = "en_US"
   end %>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/<%= @lang %>/all.js#xfbml=1&appId=254428867974812";
  fjs.parentNode.insertBefore(js, fjs);

}(document, 'script', 'facebook-jssdk'));</script>
<meta property="fb:app_id" content="254428867974812"/>

app/views/layouts/_facebook_sdk.mobile.erb
<div id="fb-root"></div>
<script>
var head = $("head").get(0);  // using jquery
var script2 = document.createElement("script");
script2.innerHTML = "window.FB = null;FB=null;";
head.appendChild(script2);
<% if locale == :ar
     @lang = "ar_AR"
   else
     @lang = "en_US"
   end %>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/<%= @lang %>/all.js#xfbml=1&appId=254428867974812";
  fjs.parentNode.insertBefore(js, fjs);

}(document, 'script', 'facebook-jssdk'));</script>
<meta property="fb:app_id" content="254428867974812"/>

app/views/layouts/_footer.html.erb
<footer>
  <hr>
  <div class="row span12">
    <div class="btn-group">

      <a class="btn" href="mailto:hello@shibshib.me">
        <i class="icon-envelope"></i>
        <%= t 'footer.contact' %>
      </a>

      <a class="btn" href="<%= about_path %>">
        <i class="icon-info-sign"></i>
        <%= t 'footer.about' %>
      </a>

      <a class="btn" href="<%= faq_path %>">
        <i class="icon-question-sign"></i>
        <%= t 'footer.faq' %>
      </a>

    </div>
  </div>
</footer>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29694324-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_google_analytics.mobile.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29694324-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_googleanalytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29694324-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<% if params[:locale] == 'ar'
     @lang = "ar_AR"
     @tlang = "ar"
   else
     @lang = "en_US"
     @tlang = "en"
   end %>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="nav-collapse">        

        &nbsp&nbsp&nbsp<a href="https://twitter.com/shibshibme" class="twitter-follow-button" data-show-count="false" data-lang="<%= @tlang %>" data-size="large">Follow</a>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
        <fb:fan profile_id="374637662568823" stream="0" connections="1" width="220px" height="61px" header="0" logobar="0" css="/assets/shibshib.css"></fb:fan>

        <!-- http://shibshib.me/assets/shibshib.css -->
        <ul class="nav pull-right">
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t 'footer.language' %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "العربية", :locale=>'ar' %></li>
            <li><%= link_to "English", :locale=>'en' %></li>
          </ul>
          </li>
          <% if user_signed_in? then %>
          <li><%= link_to "#{t 'header.new_post'}", new_post_path %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.name %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to user_path(current_user) do %><i class="icon-user"></i> <%= "#{t 'header.profile'}" %><% end %></li>
            <li><%= link_to edit_user_path(current_user) do %><i class="icon-cog"></i> <%= "#{t 'header.settings'}" %><% end %></li>
            <% if current_user.is_admin? then %>
            <li class="divider"></li>
            <li><%= link_to rails_admin_path do %><i class="icon-star"></i> <%= "#{t 'header.admin_panel'}" %><% end %></li><% end %>
            <li class="divider"></li>
            <li><%= link_to destroy_user_session_path, :method => :delete do %><i class="icon-off"></i> <%= "#{t 'header.sign_out'}" %><% end %></li>
            </ul>
          </li>

          <% else %>
          <li><%= link_to "#{t 'header.login'}", new_user_session_path %></li>
          <li><%= link_to "#{t 'header.sign_up'}", new_user_registration_path %></li>
          <% end %>
          <li><%= link_to "#{t 'header.home'}", root_path %></li>
          <%= link_to root_path do %>
          <%= image_tag("shibshib.png", :alt => "logo", :class => "brand shibshib-logo", :style=>"margin:0; padding:0") %>
          <% end %>&nbsp&nbsp&nbsp
          </ul>

      </div><!--/.nav-collapse -->

  </div>
</div>

app/views/layouts/_header.mobile.erb
<% if params[:locale] == 'ar'
     @lang = "ar_AR"
     @tlang = "ar"
   else
     @lang = "en_US"
     @tlang = "en"
   end %>
<div data-role="header" data-position="inline" class="ui-body-b">
  <h1 class="ui-btn-left" ><%= title %></h1>
  <form name="form1" >
  <select name="select" onchange="goto(this.form)" data-native-menu="false">
    <option><%= t 'mobile.options' %></option>
    <% if user_signed_in? then %>
      <option value="<%= new_post_path %>"><%="#{t 'header.new_post'}"%></option>
      <option value="<%= destroy_user_session_path %>"><%="#{t 'header.sign_out'}"%></option>
    <% else %>
      <option value="<%= new_user_session_path %>"><%="#{t 'header.login'}"%></option>
      <option value="<%= new_user_registration_path %>"><%="#{t 'header.sign_up'}"%></option>
    <% end %>
    <option value="<%= index_path %>"><%= t 'tabs.latest' %></option>
    <option value="<%= mvote_path %>"><%= t 'tabs.most_voted' %></option>
    <option value="<%= root_url(:mobile => 0) %>"><%= t 'mobile.full_version' %></option>
  </select>
  </form>
</div>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

app/views/layouts/_notice.html.erb
<div id="notices">
  <% flash.each do |key, message| %>
  <div class="<%= key %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= message %>
  </div>
  <% end %>
</div>

app/views/layouts/_noticemobile.erb
<div id="notices">
  <% flash.each do |key, message| %>
  <div class="<%= key %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= message %>
  </div>
  <% end %>
</div>

app/views/layouts/_posts_list.html.erb
<div class="row-fluid">
	<div class="span8">
		<%= link_to image_tag(post.image.url(:large), :class => 'displayed'), post %>
	</div>
	<div class="span3">
		<h2><%= post.title %></h2>
		
		<% if post.user == nil then %>
			Anonymous
		<% else %>
			<%= link_to post.user.name, user_path(post.user) %>
		<% end %> - 
		<%= "#{distance_of_time_in_words(Time.now, post.created_at)} #{t 'post.ago'}" %>
		
		<br />
		
		
		<span id="votes-<%= post.id %>"><% if(post.plusminus == 0)
			likes = "#{t 'post.no_likes'}"
		elsif(post.plusminus == 1)
			likes = "#{t 'post.one_like'}"
		elsif(post.plusminus > 1 || post.plusminus < 11)
			likes = "#{post.plusminus.to_s} #{t 'post.three_to_ten_likes'}"
		else
			likes = "#{post.plusminus.to_s} #{t 'post.many_likes'}"
		end %>
		<input class="btn disabled" type="submit" value="<%= likes %>">
		<%= link_to root_path, {:controller=> 'posts', :action=>'vote', :post_id => post.id, :class => 'btn btn-mini'}, :remote => true, :method => 'get' do %>
			<%= image_tag("like.png", :alt => "like") %>
		  <% end %>
		  
		  
		<br/>
		
		
		<input class="btn disabled" type="submit" value="<%= likes %> (COMMENTS)">
		<%= link_to root_path, {:controller=> 'posts', :action=>'vote', :post_id => post.id, :class => 'btn btn-mini'}, :remote => true, :method => 'get' do %>
			<%= image_tag("comments.png", :alt => "comments") %>
		  <% end %>
		  
		  
		<br/>
		
		<div class="social">
				<%= image_tag("tweet.png", :alt => "tweet") %> 1
				<%= image_tag("fbshare.png", :alt => "fbshare") %> 1
		</div>
		
	</div>
</div>
<HR>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="google-site-verification" content="WWR8hgOcWxopwg4ev3eND3ARP15ZBYraPc3O92KMc8w" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "shibshib" %>
    <%= stylesheet_link_tag "pagination" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>

    <style type="text/css">
      html {
        background-image:url('/assets/bg.jpg');
        background-repeat:repeat;
      }
      body {
        padding-top: 70px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <%= javascript_include_tag "application" %>
    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>

  <body>

  <p>
  <% if mobile_device?.nil? %>
  <% else %>
    <% if mobile_device? %>
        <%= link_to "#{t 'mobile.full_version'}", root_url(:mobile => 0), :rel => "external" %>
      <% else %>
        <%= link_to "#{t 'mobile.mobile_version'}", root_url(:mobile => 1), :rel => "external" %>
    <% end %>
  <% end %>
  </p>
  <%= render 'layouts/header' %>
  <%= render 'layouts/facebook_sdk' %>

  <div class="notes">
    <%= render 'layouts/notice' %>
  </div>

  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div> <!-- /container -->

  <p id="back-top"><a href="#top"><span></span><%= t 'others.back_to_top' %></a></P>

  <%= render 'layouts/google_analytics' %>
  </body>
<%= debug(params) if Rails.env.development? %>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "jquery.mobile-1.1.0.min.css" %>
  <%= stylesheet_link_tag "mobile.css" %>
  <%= stylesheet_link_tag "pagination" %>
  <%= javascript_include_tag "mobile/jquery.js" %>
  <%= javascript_include_tag "mobile/mobile.js" %>
  <%= javascript_include_tag "mobile/jquery.mobile-1.1.0.min.js" %>
</head>
<%= render 'layouts/facebook_sdk' %>
<body>
  <%= yield %>
  <%= render 'layouts/footer' %>

  <%= render 'layouts/google_analytics' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>